Implemented for List stateful Instaces, pause, resume, recycle and de…
spotinst/spotinst-sdk-java pull request #125
Opened 2022-01-19 18:07 UTC by janetlinkiruba

…allocate

_This is the default pull request template. You can customize it by adding a `pull_request_template.md` at the root of your repo or inside the `.github` folder._

# Jira Ticket

_Include a link to your Jira Ticket_
_Example: [JIRAISS-1234](https://spotinst.atlassian.net/browse/JIRAISS-1234)_

# Demo

_Please add a recording of the feature/bug fix in work. if you added new routes, the recording should show the request and response for each new/changed route_

# Checklist:
- [ ] I have filled relevant self assessment ([NodeJS](https://docs.google.com/forms/d/e/1FAIpQLSfl14u9AOBAmxVJ272tvO7XNuXE-EMvWaGcaRZalu1UAKB7RA/viewform), [Frontend](https://docs.google.com/forms/d/e/1FAIpQLSdiBPNKH81w_EkavihVL8Uwb0j7tP8PwJmLFYm2nCOQxz-1qw/viewform), [Backend](https://docs.google.com/forms/d/e/1FAIpQLSed_PsTJ5-XIWkFL6BSDE2AQRBVPmwc3PAmHZkUn-erzVI37Q/viewform?usp=sf_link))
- [ ] I have run ESlint on my changes and fixed all warnings and errors (**NodeJS & Frontend Services**)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have validated all the requirements in the Jira task were answered
- [ ] I have all neccessary approvals for the design/mini design of this task
- [ ] I have approved the API changes and granular permission patterns (documentation subtask) (**For public services only**)

2022-01-20 12:33 UTC, suganyakrishnan reviewed
Please incorporate the comments and send it for re-review.

2022-01-20 12:33 UTC, suganyakrishnan commented on src/main/java/com/spotinst/sdkjava/model/ElastigroupListStatefulInstancesDevices.java
> +@JsonFilter("PartialUpdateEntityFilter")
We dont add above JsonFilter annotations in bl - object builder classes.

2022-01-20 12:33 UTC, suganyakrishnan commented on src/main/java/com/spotinst/sdkjava/model/ApiElastigroupListStatefulInstancesDevices.java
> +package com.spotinst.sdkjava.model;
General comment: Put all the files in the respective folder structure under "model" folder.

For eg: All Api class should go under model/api/elastigroup/aws, converter class should go under model/converters/elastigroup/aws

2022-01-20 12:33 UTC, suganyakrishnan commented on src/main/java/com/spotinst/sdkjava/model/ApiElastigroupListStatefulInstancesDevices.java
> +
Add example class for stateful instance API usage since we will be adding more stateful APIs

2022-01-20 13:35 UTC, janetlinkiruba commented on src/main/java/com/spotinst/sdkjava/model/ElastigroupListStatefulInstancesDevices.java
> +public class ElastigroupListStatefulInstancesDevices implements IPartialUpdateEntity {
removed

2022-01-20 21:50 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/model/SpotinstElastigroupService.java
> +        RestResponse response = RestClient.sendPut(uri, "", headers, queryParams);
RestResponse to be casted to BaseServiceEmptyResponse before parsing to get status

BaseServiceEmptyResponse emptyResponse = getCastedResponse(response, BaseServiceEmptyResponse.class);

2022-01-20 21:50 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/model/SpotinstElastigroupService.java
> +        if (response.getStatusCode() == HttpStatus.SC_OK) {
Same comment as pause function above.

2022-01-20 21:51 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/model/SpotinstElastigroupService.java
> +        RestResponse response = RestClient.sendPut(uri, "", headers, queryParams);
Pass null, if there is no body

2022-01-20 21:53 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/model/SpotinstElastigroupService.java
> +        RestResponse response = RestClient.sendPut(uri, "", headers, queryParams);
Same comment as above.

2022-01-20 21:55 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/model/SpotinstElastigroupService.java
> +        List<ApiElastigroupListStatefulInstancesResponse> statefulInstancesList = null;
Shouldn't it be initialized to new LinkedList<>();

2022-01-20 22:00 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/model/converters/elastigroup/aws/StatefulElastigroupConverter.java
> +import com.spotinst.sdkjava.model.ElastigroupConverter;
Why this import is needed?

2022-01-20 22:01 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/model/SpotinstElastigroupRepo.java
> +    public RepoGenericResponse<Boolean> pauseStatefulInstance(String elastigroupId, String statefulInstanceId,
Properly align code in this file.

2022-01-20 22:05 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/model/ElastigroupConverter.java
> +
Didn't understand this change.

2022-01-20 22:09 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/example/elastigroup/aws/StatefulElastigroupUsageExample.java
> +        return pauseStatus;
Add else condition and corresponding print statement for operation failed. Applicable to all similar functions in this file.

2022-01-20 22:10 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/example/elastigroup/aws/StatefulElastigroupUsageExample.java
> +        for (ElastigroupListStatefulInstancesResponse statusData : elastigroupStatefulInstances) {
Change variable name "statusData" to "instance"

2022-01-20 22:11 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/example/elastigroup/aws/StatefulElastigroupUsageExample.java
> +            System.out.println(String.format("Stateful Instance private IP: %s", statusData.getPrivateIp()));
Print all parameters. Especially interested to see if createdAt and LaunchedAt parameters are correctly returned or not.

2022-01-20 22:13 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/example/elastigroup/aws/StatefulElastigroupUsageExample.java
> +        String statefulId = null;
This for loop is redundant, the information is already printed in the called function. No need to retrieve the ID here. We are not doing any operation with it.

2022-01-20 22:14 UTC, anuragsharma-123 requested changes
Please review and rework on the comments.

2022-01-21 05:39 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/example/elastigroup/aws/StatefulElastigroupUsageExample.java
> +            System.out.println(String.format("Stateful Instance Devices: %s", instance.getDevices()));
getDevice() is not a string. Can we iterate and print all 3 string fields?

2022-01-21 10:22 UTC, anuragsharma-123 approved these changes

2022-01-21 10:22 UTC, merged