ManagedInstance api sdk implimentation
spotinst/spotinst-sdk-java pull request #234
Opened 2023-01-19 04:13 UTC by ramrutha497

Checklist
---------

JIRA Ticket -

Checklist (Please mark Yes/No/NA for each of the questions below) -

- I have provided clear and detailed explanation of changes made in the proposed PR : No
- I have compiled the code successfully my laptop : No
- I have written examples to demonstrates the usage of the newly implemented APIs : No
- I have incremented the release version : No
- I have run the Intellij Code Analysis on newly added code and fixed all (valid) reported issues : No

OR

- I have taken approval from scrum master or project manager for skipping any of the items above : No

2023-01-22 21:27 UTC, anuragsharma-123 commented on src/main/java/com/spotinst/sdkjava/model/ISpotAwsManagedInstanceRepo.java
> +    RepoGenericResponse<GetInstanceCost> getInstanceCosts(String migrationId, String fromDate, String toDate, String authToken, String account);
first parameter should be managedInstanceId

2023-01-26 17:50 UTC, chandra1-n commented on src/main/java/com/spotinst/sdkjava/model/SpotAwsManagedInstanceClient.java
> +    public GetInstanceCost getManagedInstanceCosts(String managedInstanceId, String fromDate, String toDate) {
"aggregationPeriod" query param is missing

2023-01-26 17:51 UTC, chandra1-n commented on src/main/java/com/spotinst/sdkjava/model/service/aws/managedInstance/AwsManagedInstanceService.java
> +                                                                          String account) throws SpotinstHttpException {
"aggregationPeriod" query param is missing

2023-01-26 17:57 UTC, chandra1-n commented on src/main/java/com/spotinst/sdkjava/model/api/aws/managedInstance/ApiRunning.java
> +
re-utilize this class, as ApiSavings class also contains same attributes

2023-01-26 17:58 UTC, chandra1-n commented on src/main/java/com/spotinst/sdkjava/model/api/aws/managedInstance/ApiSavings.java
> +package com.spotinst.sdkjava.model.api.aws.managedInstance;
no need of this class, ApiRunning class can be re-utilized

2023-01-26 18:00 UTC, chandra1-n commented on src/main/java/com/spotinst/sdkjava/model/bl/aws/managedInstance/Savings.java
> +
same attributes are available in Running class, re-utilize the same class

2023-01-26 18:02 UTC, chandra1-n commented on src/main/java/com/spotinst/sdkjava/model/converters/aws/managedInstance/AwsManagedInstanceConverter.java
> +
add running class, cost class conversion as well

2023-01-26 18:03 UTC, chandra1-n commented on src/main/java/com/spotinst/sdkjava/model/repo/aws/managedInstance/SpotAwsManagedInstanceRepo.java
> +        RepoGenericResponse<GetInstanceCost> instanceCosts;
change first parameter to managedInstanceId

2023-01-26 18:05 UTC, chandra1-n commented on src/main/java/com/spotinst/sdkjava/model/requests/aws/managedInstance/AwsManagedInstanceUpdateRequest.java
> +        managedInstanceUpdateRequest.put("managedInstanceUpdate", apiManagedInstanceUpdate);
"managedInstanceUpdate" should be renamed to "managedInstanceStates"

2023-01-26 18:06 UTC, chandra1-n commented on src/main/java/com/spotinst/sdkjava/model/responses/aws/managedInstance/AwsManagedInstanceGetInstanceCostsApiRespponse.java
> +package com.spotinst.sdkjava.model.responses.aws.managedInstance;
typo in file name

2023-01-26 18:06 UTC, chandra1-n commented on src/main/java/com/spotinst/sdkjava/model/service/aws/managedInstance/AwsManagedInstanceService.java
> +        AwsManagedInstanceGetInstanceCostsApiRespponse managedInstanceStatusResponse =
typo in name api response name

2023-01-26 18:11 UTC, chandra1-n commented on src/main/java/com/spotinst/sdkjava/model/service/aws/managedInstance/AwsManagedInstanceService.java
> +        AwsManagedInstanceApiResponse managedInstanceUpdateResponse =
it's a boolean response, no need to caste with AwsManagedInstanceApiResponse

2023-01-26 18:12 UTC, chandra1-n requested changes
please fix the review comments

2023-02-24 08:05 UTC, anuragsharma-123 commented
These APIs are implemented and tested in Python-SDK. Closing this PR.

2023-02-24 08:05 UTC, closed without merging